In [1]:
import numpy
i = numpy.array([10,20,30,40])
print(i)

[10 20 30 40]


In [2]:
import numpy
j = numpy.array([10,20,30,40])
print(j)
print(type(j))

[10 20 30 40]
<class 'numpy.ndarray'>


In [4]:
import numpy
i = numpy.array([10,20,30,40],ndmin=5)
print(i)

[[[[[10 20 30 40]]]]]


In [5]:
import numpy as np
i = np.array([10,20,30,40])
print(i)

[10 20 30 40]


In [6]:
import numpy
i = numpy.array([10,20,30,40])
print(i[0:5])

[10 20 30 40]


In [4]:
import numpy as np  
a = np.array([[1,2],[3,4],[5,6]])  
print("printing the original array..")  
print(a)  
a=a.reshape(2,3)  
print("printing the reshaped array..")  
print(a)  

printing the original array..
[[1 2]
 [3 4]
 [5 6]]
printing the reshaped array..
[[1 2 3]
 [4 5 6]]
